#!/usr/bin/env node
// Idempotent <head> SEO injector for the committed static pages.
//
// Adds a marker-delimited block to every page containing:
//   canonical, robots, OpenGraph, Twitter card, and JSON-LD structured data.
//
// Re-running REPLACES the existing block rather than duplicating it, so this is
// safe to run any number of times. Run it after adding pages or editing titles:
//
//   node scripts/inject-seo.js
//
// Ghost-generated blog posts are NOT touched here — their head tags live in
// scripts/post-template.html and are filled in by build-blog.js.

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const CFG = JSON.parse(fs.readFileSync(path.join(__dirname, 'seo-config.json'), 'utf8'));
const LEGACY = JSON.parse(fs.readFileSync(path.join(__dirname, 'legacy-posts.json'), 'utf8'));

const START = '<!-- SEO:START (generated by scripts/inject-seo.js — do not hand-edit) -->';
const END = '<!-- SEO:END -->';

const SKIP_DIRS = new Set(['node_modules', '.git', 'scripts', '.vercel']);
const SKIP_FILES = new Set(['blog/_template.html']);

// ---------------------------------------------------------------- helpers

function esc(s) {
  return String(s ?? '')
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// Titles/descriptions read out of source HTML may already contain entities like
// &amp;. Decode before re-escaping so we never double-encode.
function decode(s) {
  return String(s ?? '')
    .replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&apos;/g, "'")
    .replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&');
}

function walk(dir, out = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.') && entry.name !== '.') continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue;
      walk(full, out);
    } else if (entry.name.endsWith('.html')) {
      out.push(full);
    }
  }
  return out;
}

// /home/.../appsurd/about/index.html -> "/about/"
// /home/.../appsurd/services/advisory.html -> "/services/advisory.html"
function urlPathFor(rel) {
  const parts = rel.split(path.sep);
  const file = parts.pop();
  if (file === 'index.html') {
    return parts.length ? `/${parts.join('/')}/` : '/';
  }
  return `/${[...parts, file].join('/')}`;
}

function pick(re, html) {
  const m = html.match(re);
  return m ? decode(m[1].trim()) : '';
}

function jsonld(obj) {
  // JSON-LD lives in a <script>, so the only escaping that matters is
  // preventing a literal </script> from closing the block early.
  return `<script type="application/ld+json">\n${JSON.stringify(obj, null, 2)
    .replace(/<\//g, '<\\/')}\n</script>`;
}

// ---------------------------------------------------------------- schema

const ORG_ID = `${CFG.origin}/#organization`;
const SITE_ID = `${CFG.origin}/#website`;

function organization() {
  const address = { '@type': 'PostalAddress' };
  if (CFG.streetAddress) address.streetAddress = CFG.streetAddress;
  if (CFG.addressLocality) address.addressLocality = CFG.addressLocality;
  if (CFG.addressRegion) address.addressRegion = CFG.addressRegion;
  if (CFG.postalCode) address.postalCode = CFG.postalCode;
  if (CFG.addressCountry) address.addressCountry = CFG.addressCountry;

  // With a real street address the entity qualifies as a LocalBusiness, which
  // is what local search rewards. Without one, stay a plain Organization.
  const types = CFG.streetAddress
    ? ['Organization', 'ProfessionalService']
    : 'Organization';

  const org = {
    '@type': types,
    '@id': ORG_ID,
    name: CFG.siteName,
    legalName: CFG.legalName,
    url: `${CFG.origin}/`,
    description: CFG.description,
    email: CFG.email,
    foundingDate: CFG.foundingDate,
    logo: { '@type': 'ImageObject', url: CFG.origin + CFG.logo },
    image: CFG.origin + CFG.defaultImage,
    address,
    areaServed: CFG.areaServed.map((n) => ({ '@type': 'Place', name: n })),
    knowsAbout: CFG.knowsAbout,
    sameAs: CFG.sameAs,
  };
  if (CFG.telephone) org.telephone = CFG.telephone;
  if (CFG.parentOrganization) {
    org.parentOrganization = { '@type': 'Organization', name: CFG.parentOrganization };
  }
  return org;
}

function breadcrumbs(urlPath, title) {
  const segs = urlPath.replace(/^\/|\/$/g, '').split('/').filter(Boolean);
  const items = [{
    '@type': 'ListItem', position: 1, name: 'Home', item: `${CFG.origin}/`,
  }];
  let acc = '';
  segs.forEach((seg, i) => {
    acc += `/${seg}`;
    const last = i === segs.length - 1;
    const name = last
      ? title.replace(/\s+[—–-]\s+Appsurd.*$/, '').trim()
      : seg.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
    items.push({
      '@type': 'ListItem',
      position: i + 2,
      name,
      item: CFG.origin + acc + (last && !seg.endsWith('.html') ? '/' : ''),
    });
  });
  return { '@type': 'BreadcrumbList', '@id': `${CFG.origin}${urlPath}#breadcrumb`, itemListElement: items };
}

function graphFor({ urlPath, title, description, rel }) {
  const pageUrl = CFG.origin + urlPath;
  const cleanTitle = title.replace(/\s+[—–-]\s+Appsurd.*$/, '').trim() || CFG.siteName;
  const graph = [];

  if (urlPath === '/') {
    graph.push(organization());
    graph.push({
      '@type': 'WebSite',
      '@id': SITE_ID,
      url: `${CFG.origin}/`,
      name: CFG.siteName,
      description: description || CFG.description,
      publisher: { '@id': ORG_ID },
      inLanguage: 'en-US',
    });
    graph.push({
      '@type': 'WebPage',
      '@id': `${pageUrl}#webpage`,
      url: pageUrl,
      name: title,
      description: description || CFG.description,
      isPartOf: { '@id': SITE_ID },
      about: { '@id': ORG_ID },
      inLanguage: 'en-US',
    });
    return graph;
  }

  const legacyPost = LEGACY.find((p) => p.href === urlPath);
  const isTeamMember = rel.startsWith(`team${path.sep}`) && !rel.endsWith('index.html');
  const isService = rel.startsWith(`services${path.sep}`) && !rel.endsWith('index.html');
  const isCase = rel.startsWith(`work${path.sep}`) && !rel.endsWith('index.html');

  if (legacyPost) {
    graph.push({
      '@type': 'BlogPosting',
      '@id': `${pageUrl}#article`,
      url: pageUrl,
      headline: cleanTitle,
      description,
      datePublished: legacyPost.dateISO,
      dateModified: legacyPost.dateISO,
      author: { '@type': 'Person', name: decode(legacyPost.authorHtml).split(',')[0].trim() },
      publisher: { '@id': ORG_ID },
      isPartOf: { '@id': SITE_ID },
      mainEntityOfPage: pageUrl,
      image: CFG.origin + CFG.defaultImage,
      inLanguage: 'en-US',
    });
  } else if (isTeamMember) {
    graph.push({
      '@type': 'Person',
      '@id': `${pageUrl}#person`,
      url: pageUrl,
      name: cleanTitle,
      description,
      worksFor: { '@id': ORG_ID },
    });
  } else if (isService) {
    graph.push({
      '@type': 'Service',
      '@id': `${pageUrl}#service`,
      url: pageUrl,
      name: cleanTitle,
      description,
      serviceType: cleanTitle,
      provider: { '@id': ORG_ID },
      areaServed: CFG.areaServed.map((n) => ({ '@type': 'Place', name: n })),
    });
  } else if (isCase) {
    graph.push({
      '@type': 'Article',
      '@id': `${pageUrl}#article`,
      url: pageUrl,
      headline: cleanTitle,
      description,
      author: { '@id': ORG_ID },
      publisher: { '@id': ORG_ID },
      isPartOf: { '@id': SITE_ID },
      inLanguage: 'en-US',
    });
  }

  graph.push({
    '@type': 'WebPage',
    '@id': `${pageUrl}#webpage`,
    url: pageUrl,
    name: title,
    description: description || CFG.description,
    isPartOf: { '@id': SITE_ID },
    breadcrumb: { '@id': `${pageUrl}#breadcrumb` },
    inLanguage: 'en-US',
  });
  graph.push(breadcrumbs(urlPath, title));

  return graph;
}

// ---------------------------------------------------------------- block

function buildBlock({ urlPath, title, description, rel }) {
  const pageUrl = CFG.origin + urlPath;
  const img = CFG.origin + CFG.defaultImage;
  const desc = description || CFG.description;
  const isArticle = LEGACY.some((p) => p.href === urlPath);

  const lines = [
    START,
    `<link rel="canonical" href="${esc(pageUrl)}">`,
    '<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">',
    `<meta property="og:type" content="${isArticle ? 'article' : 'website'}">`,
    `<meta property="og:site_name" content="${esc(CFG.siteName)}">`,
    '<meta property="og:locale" content="en_US">',
    `<meta property="og:url" content="${esc(pageUrl)}">`,
    `<meta property="og:title" content="${esc(title)}">`,
    `<meta property="og:description" content="${esc(desc)}">`,
    `<meta property="og:image" content="${esc(img)}">`,
    '<meta property="og:image:width" content="1200">',
    '<meta property="og:image:height" content="630">',
    `<meta property="og:image:alt" content="${esc(`${CFG.siteName} — ${CFG.tagline}`)}">`,
    '<meta name="twitter:card" content="summary_large_image">',
    `<meta name="twitter:site" content="${esc(CFG.twitterHandle)}">`,
    `<meta name="twitter:title" content="${esc(title)}">`,
    `<meta name="twitter:description" content="${esc(desc)}">`,
    `<meta name="twitter:image" content="${esc(img)}">`,
    jsonld({ '@context': 'https://schema.org', '@graph': graphFor({ urlPath, title, description: desc, rel }) }),
    END,
  ];
  return lines.join('\n');
}

// ---------------------------------------------------------------- main

function main() {
  const files = walk(ROOT).filter((f) => !SKIP_FILES.has(path.relative(ROOT, f).split(path.sep).join('/')));
  let injected = 0;
  let updated = 0;
  let addedDesc = 0;

  for (const file of files) {
    const rel = path.relative(ROOT, file);
    let html = fs.readFileSync(file, 'utf8');

    const urlPath = urlPathFor(rel);
    const title = pick(/<title>([\s\S]*?)<\/title>/i, html) || CFG.siteName;
    let description = pick(/<meta\s+name="description"\s+content="([\s\S]*?)"\s*\/?>/i, html);

    // Home page shipped without a meta description — add one.
    if (!description) {
      description = CFG.description;
      const legacy = LEGACY.find((p) => p.href === urlPath);
      if (legacy) description = decode(legacy.excerptHtml || '') || CFG.description;
      html = html.replace(/(<title>[\s\S]*?<\/title>)/i,
        `$1\n<meta name="description" content="${esc(description)}">`);
      addedDesc += 1;
    }

    const block = buildBlock({ urlPath, title, description, rel });

    const a = html.indexOf(START);
    const b = html.indexOf(END);
    if (a !== -1 && b !== -1 && b > a) {
      html = html.slice(0, a) + block + html.slice(b + END.length);
      updated += 1;
    } else {
      const anchor = html.match(/<meta\s+name="description"[\s\S]*?>/i)
        || html.match(/<title>[\s\S]*?<\/title>/i);
      if (!anchor) {
        console.warn(`inject-seo: no <title> or description in ${rel} — skipped`);
        continue;
      }
      const at = anchor.index + anchor[0].length;
      html = `${html.slice(0, at)}\n${block}${html.slice(at)}`;
      injected += 1;
    }

    fs.writeFileSync(file, html);
  }

  console.log(`inject-seo: ${injected} page(s) injected, ${updated} refreshed, `
    + `${addedDesc} meta description(s) added, ${files.length} scanned.`);
}

main();
